'use client'

import { useEffect, useMemo, useState } from 'react'
import { Activity, CalendarDays, DatabaseZap, Download, RotateCw, TrendingUp, UsersRound } from 'lucide-react'
import AppShell, { PageHeading, Panel, StatusPill } from '@/components/app-shell'
import { ValidateAuth } from '@/lib/auth'
import { LoadingPanel, useSaasDashboard, useUsageAnalytics } from '@/lib/use-saas'
import { ExportUsageCsv, RecordUsage } from '@/lib/dtos'
import { client as gateway } from '@/lib/gateway'

const formatUnits=(key?:string,value?:number)=>{
  const n=value??0
  if(key==='storage.bytes')return n>=1024**3?`${(n/1024**3).toFixed(1)} GB`:n>=1024**2?`${(n/1024**2).toFixed(1)} MB`:`${n.toLocaleString()} B`
  return n.toLocaleString()
}

function UsagePage() {
  const {data,error,loading,refresh}=useSaasDashboard()
  const [busy,setBusy]=useState(false); const [notice,setNotice]=useState<string>()
  const [meter,setMeter]=useState('api.requests')
  const available=useMemo(()=>data?.usage?.map(x=>x.meterKey).filter(Boolean) as string[]|undefined,[data?.usage])
  const usageRevision=useMemo(()=>data?.usage?.map(x=>`${x.meterKey}:${x.usedUnits}:${x.reservedUnits}`).join('|')??'',[data?.usage])
  const {data:analytics,error:analyticsError,loading:analyticsLoading}=useUsageAnalytics(meter,30,!loading,usageRevision)
  useEffect(()=>{if(!loading&&available?.length&&!available.includes(meter))setMeter(available[0])},[loading,available,meter])
  const record=async()=>{setBusy(true);setNotice(undefined);const api=await gateway.api(new RecordUsage({meterKey:'api.requests',units:10,idempotencyKey:crypto.randomUUID(),metadataJson:'{"source":"usage-dashboard-demo"}'}));setNotice(api.succeeded?'Recorded 10 idempotent API request units.':api.error?.message);setBusy(false);if(api.succeeded)refresh()}
  const exportCsv=async()=>{setBusy(true);setNotice(undefined);try{const blob=await gateway.get(new ExportUsageCsv({meterKey:meter,days:30}));const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`usage-${meter}-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}catch(e){setNotice(e instanceof Error?e.message:'Unable to export usage.')}finally{setBusy(false)}}
  const max=useMemo(()=>Math.max(1,...(analytics?.series?.map(x=>x.units??0)??[])),[analytics])
  if(loading)return <AppShell><LoadingPanel/></AppShell>
  const canUseApi=data?.entitlements?.some(x=>x.key==='api.access'&&x.enabled)===true
  return <AppShell workspaceName={data?.workspace?.name}><PageHeading eyebrow="Plan capacity & metering" title="Usage" description="Understand current gauges, period counters, reserved capacity, forecast demand, and the people driving consumption." action={<div className="flex flex-wrap gap-2"><button onClick={exportCsv} disabled={busy||!meter} className="inline-flex items-center gap-2 rounded-[10px] border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 disabled:opacity-60 dark:border-white/15 dark:bg-white/5 dark:text-white"><Download className="h-4 w-4"/>Export CSV</button><button onClick={record} disabled={busy||!canUseApi||data?.subscription?.accessMode==='ReadOnly'} title={!canUseApi?'API access requires a paid plan':undefined} className="inline-flex items-center gap-2 rounded-[10px] bg-[#0b5cff] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><DatabaseZap className="h-4 w-4"/>{busy?'Working…':canUseApi?'Record 10 demo API calls':'API access unavailable'}</button></div>}/>{(error||analyticsError)&&<Panel className="mb-5 p-4 text-sm text-red-600">{error||analyticsError}</Panel>}{notice&&<Panel className="mb-5 border-blue-200 bg-blue-50 p-4 text-sm text-blue-800 dark:border-blue-400/20 dark:bg-blue-400/10 dark:text-blue-200">{notice}</Panel>}
    <div className="grid gap-5 lg:grid-cols-2">{data?.usage?.map(item=><button onClick={()=>item.meterKey&&setMeter(item.meterKey)} key={item.meterKey} className="text-left"><Panel className={`h-full p-6 transition ${meter===item.meterKey?'border-blue-300 ring-2 ring-blue-100 dark:border-blue-400/40 dark:ring-blue-400/10':''}`}><div className="flex items-start justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-[#0b5cff] dark:bg-blue-400/10"><Activity className="h-5 w-5"/></span><div><h2 className="font-semibold">{item.displayName}</h2><p className="mt-1 font-mono text-[10px] text-slate-400">{item.meterKey}</p></div></div><div className="flex gap-2"><StatusPill tone="slate">{item.kind}</StatusPill><StatusPill tone={(item.percentUsed||0)>80?'amber':'green'}>{item.enforcement}</StatusPill></div></div><div className="mt-8 flex items-end justify-between"><p><span className="text-4xl font-semibold tracking-[-.05em]">{formatUnits(item.meterKey,item.usedUnits)}</span><span className="ml-2 text-sm text-slate-400">/ {item.allowance==null?'unlimited':formatUnits(item.meterKey,item.allowance)}</span></p><p className="text-sm font-semibold text-[#0b5cff]">{item.percentUsed}%</p></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#0b5cff] to-[#86efcd]" style={{width:`${Math.min(100,Math.max(0,item.percentUsed||0))}%`}}/></div><div className="mt-6 grid grid-cols-3 gap-3 text-xs text-slate-500"><div className="rounded-lg bg-slate-50 p-3 dark:bg-white/[.035]"><CalendarDays className="mb-2 h-4 w-4"/>{item.reset==='Never'?'No reset':`Resets ${item.periodEnd?new Date(item.periodEnd).toLocaleDateString():'—'}`}</div><div className="rounded-lg bg-slate-50 p-3 dark:bg-white/[.035]"><RotateCw className="mb-2 h-4 w-4"/>{item.remainingUnits===Number.MAX_SAFE_INTEGER?'Unlimited':`${formatUnits(item.meterKey,item.remainingUnits)} left`}</div><div className="rounded-lg bg-slate-50 p-3 dark:bg-white/[.035]"><DatabaseZap className="mb-2 h-4 w-4"/>{formatUnits(item.meterKey,item.reservedUnits)} reserved</div></div></Panel></button>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <Panel className="p-6"><div className="flex items-start justify-between"><div><h2 className="font-semibold">30-day demand</h2><p className="mt-1 font-mono text-[10px] text-slate-400">{meter}</p></div><StatusPill tone="blue">Daily</StatusPill></div>{analyticsLoading?<div className="grid h-56 place-items-center"><span className="h-7 w-7 animate-spin rounded-full border-2 border-blue-100 border-t-[#0b5cff]"/></div>:<><div className="mt-7 flex h-48 items-end gap-1.5 border-b border-slate-200 dark:border-white/10">{analytics?.series?.map(point=><div key={point.date} title={`${point.date}: ${formatUnits(meter,point.units)}`} className="group flex h-full min-w-0 flex-1 items-end"><span className="w-full rounded-t-sm bg-blue-100 transition group-hover:bg-[#0b5cff] dark:bg-blue-400/15" style={{height:`${Math.max(point.units?3:0,((point.units??0)/max)*100)}%`}}/></div>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4 dark:bg-white/[.035]"><TrendingUp className="h-4 w-4 text-[#0b5cff]"/><p className="mt-3 text-lg font-semibold">{formatUnits(meter,analytics?.projectedPeriodEndUnits)}</p><p className="text-xs text-slate-400">Projected period end</p></div><div className="rounded-xl bg-slate-50 p-4 dark:bg-white/[.035]"><DatabaseZap className="h-4 w-4 text-[#0b5cff]"/><p className="mt-3 text-lg font-semibold">{analytics?.rejectedOperations??0}</p><p className="text-xs text-slate-400">Rejected operations</p></div><div className="rounded-xl bg-slate-50 p-4 dark:bg-white/[.035]"><Activity className="h-4 w-4 text-[#0b5cff]"/><p className="mt-3 text-lg font-semibold">{formatUnits(meter,analytics?.series?.reduce((sum,x)=>sum+(x.units??0),0))}</p><p className="text-xs text-slate-400">30-day activity</p></div></div></>}</Panel>
      <Panel className="p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Usage by member</h2><p className="mt-1 text-xs text-slate-400">Top actors for this meter</p></div><UsersRound className="h-5 w-5 text-[#0b5cff]"/></div><div className="mt-6 space-y-4">{analytics?.byUser?.length?analytics.byUser.map((item,index)=><div key={item.key}><div className="flex items-center justify-between gap-3 text-xs"><span className="truncate font-mono text-slate-500 dark:text-slate-400">{item.label||'system'}</span><strong>{formatUnits(meter,item.units)}</strong></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full rounded-full bg-[#0b5cff]" style={{width:`${Math.max(5,100-index*14)}%`}}/></div></div>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-white/[.035]">No attributed events in this window. Gauge values can exist without period events.</p>}</div></Panel>
    </div>
    <Panel className="mt-5 p-6"><h2 className="font-semibold">How quota enforcement works</h2><div className="mt-5 grid gap-5 text-sm leading-6 text-slate-500 md:grid-cols-3 dark:text-slate-400"><p><strong className="block text-slate-900 dark:text-white">1. Resolve entitlement</strong>Customer override takes precedence over the pinned plan version.</p><p><strong className="block text-slate-900 dark:text-white">2. Reserve, settle, release</strong>Expensive work reserves capacity first, then records actual consumption idempotently.</p><p><strong className="block text-slate-900 dark:text-white">3. Enforce locally</strong>No Stripe request is made on the authorization hot path.</p></div></Panel>
  </AppShell>
}
export default ValidateAuth(UsagePage)
