'use client'

import { FormEvent, useState } from 'react'
import { useClient } from '@servicestack/react'
import { Building2, ExternalLink, Globe2, LockKeyhole, Plus, UserRound } from 'lucide-react'
import AppShell,{PageHeading,Panel,StatusPill} from '@/components/app-shell'
import {ValidateAuth,appAuth} from '@/lib/auth'
import {LoadingPanel,useSaasDashboard} from '@/lib/use-saas'
import { CreateOrganization, UpdateWorkspaceProfile } from '@/lib/dtos'
import WorkspaceLifecycle from '@/components/workspace-lifecycle'

function SettingsPage(){
  const client=useClient(); const {user}=appAuth(); const {data,loading,refresh}=useSaasDashboard(); const [notice,setNotice]=useState<string>(); const [createNotice,setCreateNotice]=useState<string>(); const [creating,setCreating]=useState(false)
  const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const api=await client.api(new UpdateWorkspaceProfile({name:String(f.get('name')),slug:String(f.get('slug')),billingEmail:String(f.get('billingEmail'))}));setNotice(api.succeeded?'Organization saved.':api.error?.message);if(api.succeeded)refresh()}
  const createOrganization=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setCreating(true);setCreateNotice(undefined);const f=new FormData(e.currentTarget);const api=await client.api(new CreateOrganization({name:String(f.get('organizationName')),billingEmail:String(f.get('organizationBillingEmail')||'')||undefined}));if(api.succeeded){window.location.href='/dashboard';return}setCreateNotice(api.error?.message??'Unable to create the organization.');setCreating(false)}
  if(loading)return <AppShell><LoadingPanel/></AppShell>
  return <AppShell workspaceName={data?.workspace?.name}>
    <PageHeading eyebrow="Account configuration" title="Settings" description="Manage your organization and personal account."/>
    <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
      <Panel className="p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-[#0b5cff] dark:bg-blue-400/10"><Building2 className="h-5 w-5"/></span><div><h2 className="font-semibold">Organization</h2><p className="mt-1 text-xs text-slate-400">Shared with members and used for billing</p></div></div><form onSubmit={save} className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Organization name<input name="name" required defaultValue={data?.workspace?.name} className="mt-2 block w-full rounded-[10px] border-slate-200 bg-white text-sm dark:border-white/10 dark:bg-white/5"/></label><input type="hidden" name="slug" value={data?.workspace?.slug ?? ''}/><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Billing email<input name="billingEmail" type="email" defaultValue={data?.workspace?.billingEmail} className="mt-2 block w-full rounded-[10px] border-slate-200 bg-white text-sm dark:border-white/10 dark:bg-white/5"/></label><div className="flex items-center gap-4 sm:col-span-2"><button className="rounded-[10px] bg-[#0b5cff] px-4 py-2.5 text-sm font-semibold text-white">Save organization</button>{notice&&<p className="text-xs text-[#0b5cff]">{notice}</p>}</div></form></Panel>
      <div className="space-y-5"><Panel className="p-6"><UserRound className="h-5 w-5 text-[#0b5cff]"/><h2 className="mt-4 font-semibold">Personal account</h2><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{user?.userName}</p><a href="/Identity/Account/Manage" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#0b5cff]">Manage identity <ExternalLink className="h-4 w-4"/></a></Panel><Panel className="p-6"><div className="flex items-center justify-between"><Globe2 className="h-5 w-5 text-[#0b5cff]"/><StatusPill>UTC</StatusPill></div><h2 className="mt-4 font-semibold">Usage timezone</h2><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">Free-plan periods reset on calendar month boundaries in UTC.</p></Panel><Panel className="p-6"><LockKeyhole className="h-5 w-5 text-[#0b5cff]"/><h2 className="mt-4 font-semibold">Security</h2><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">Password, email confirmation, and recovery are provided by Identity.</p></Panel></div>
    </div>
    <div id="create-organization"><Panel className="mt-5 p-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-[#86efcd]"><Plus className="h-5 w-5"/></span><div><h2 className="font-semibold">Create another organization</h2><p className="mt-1 text-sm leading-6 text-slate-500 dark:text-slate-400">Create a separate organization with its own members, plan, usage, files, and API keys. You will become its Owner.</p></div></div><form onSubmit={createOrganization} className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Organization name<input name="organizationName" minLength={2} maxLength={100} required placeholder="Example, Inc." className="mt-2 block w-full rounded-[10px] border-slate-200 bg-white text-sm dark:border-white/10 dark:bg-white/5"/></label><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Billing email <span className="font-normal text-slate-400">(optional)</span><input name="organizationBillingEmail" type="email" placeholder={user?.userName} className="mt-2 block w-full rounded-[10px] border-slate-200 bg-white text-sm dark:border-white/10 dark:bg-white/5"/></label><div className="flex items-center gap-4 sm:col-span-2"><button disabled={creating} className="inline-flex items-center gap-2 rounded-[10px] bg-[#0b5cff] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Plus className="h-4 w-4"/>{creating?'Creating…':'Create organization'}</button>{createNotice&&<p className="text-xs text-red-600 dark:text-red-400">{createNotice}</p>}</div></form></Panel></div>
    <WorkspaceLifecycle workspaceName={data?.workspace?.name} role={data?.memberRole}/>
  </AppShell>
}
export default ValidateAuth(SettingsPage)
